### ISSUE TITLE
Having a Wiki would be better.

### ISSUE THREAD

**Issue by sourcepirate** [minervaproject/pykurento#2]
I really appreciate your work on pykurento. can we see some wiki for it.

**Comment by vaibhavmule** [comment]
@plasmashadow same from me.. but could you please tell what exactly you want in wiki.

**Comment by genehallman** [comment]
Hey @plasmashadow & @vaibhavmule,

I started this project as an experiment here at minervaproject and was a little shocked to see that people have found it and are playing with it. I haven't been able to get back to it since the initial commits but the plan is to continue development on this in the next few weeks since the we're prioritizing our Kurento work right now.

I'd love to have outside contributors (I've already merged @vaibhavmule 's PR), so if you'd like to help build out the wiki, I'm totally open to that.

Thanks for the eyes on it!

**Comment by sourcepirate** [comment]
@genehallman can you create a chatroom for this repo in gitter.
